create table meteo(
id INTEGER PRIMARY KEY AUTOINCREMENT,
datetime DATETIME,
lat FLOAT,
lon FLOAT,
lat2 VARCHAR(16),
lon2 VARCHAR(16),
altitude FLOAT,
gps_qual INTEGER,
num_sats INTEGER,
heading FLOAT,
navigation_dir FLOAT,
navigation_speed FLOAT,
faa_mode VARCHAR(1),
airtemp FLOAT,
pressure FLOAT,
rel_humidity FLOAT,
wind_speed FLOAT,
wind_dir FLOAT)
